services:
  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: development
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app_host
    environment:
      - DATA_PATH=/app_host/analysis_data_09-04-2026_2(in).csv
